name:                chip8
version:             0.1.0.0
github:              "deathgrindfreak/chip8"
license:             BSD3
author:              "Cooper Bell"
maintainer:          "john.cooper.bell@gmail.com"
copyright:           "2021 Cooper Bell"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/deathgrindfreak/chip8#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- sdl2
- linear
- StateVar

library:
  source-dirs: src

executables:
  chip8-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chip8

tests:
  chip8-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chip8
